Backend Comments Test Cases
UNLV-CS472-672/2024-F-GROUP3-RebelHub pull request #45
Opened 2024-11-01 05:11 UTC by misherwa

*Please complete the checklist so the group can quickly understand your PR.*

### Category
- [ ] **Feature**
- [ ] **Bug Fix**
- [x] **Testing**
- [ ] **Documentation**
- [ ] **Other**

### Domain
- [ ] **Frontend**
- [x] **Backend**
- [ ] **Both**

### Description
Provide test case coverage for all the files in the Comments backend folder. I have completed test coverage for models.py, and now need to finish the coverage for serializers.py and views,py.

### Related Issue(s)
#44 "Backend Comments Need Test cases"

### New Additions
No new files

### Modifications
-tests.py (Added test coverage for models.py)

### New Dependencies
None

### Visuals
![q](https://github.com/user-attachments/assets/9d0fa1e0-9e22-4fe8-82af-cf0a1a728f6a)
Here is a current view of the coverage results for the Comments folder. As mentioned above, need to finish the coverage for serializers.py and views,py.

### Architecture of Your Changes
No modifications to an existing system, only improvements to test coverage results.

### Usage and Integration
Just used to increase our overall test coverage percentage,

### Testing
Describe the tests performed to ensure your changes function as expected. This section should include:
- **Testing Approach**: Applied unit testing 
- **Edge Cases**: Currently need to add coverage for test cases that involve the serializers.py and views,py files in the Comments backend folder.
- **Test Commands**: Make sure to do "pip install coverage", then in the backend folder do "python manage.py test". Lastly, you can do "coverage report" for the result

### Mentions
N/A

2024-11-03 19:34 UTC, thecatfour commented
I don't think "test_create_comment" is the best name for this test case. The name implies that the test is creating a comment, but the comment is created in the setUp function. Something like "test_check_setup_comment" might be more accurate.

![image](https://github.com/user-attachments/assets/1eeaa28c-5a32-477b-b180-573a15b7f0e4)

2024-11-04 10:16 UTC, leed85 reviewed
Good tests, I think we need to discuss the architecture of comments a bit, should we allow constant reply of comments(i.e. reddit style where you can reply to a specific comment or a reply and it constantly branches off from there) or like youtube where you just @ the person in the comments as a reply

2024-11-09 23:13 UTC, misherwa commented
> test_check_setup_comment

Yeah that makes sense, I changed "test_create_comment" to "test_check_setup_comment"

2024-11-10 03:20 UTC, misherwa commented
> Good tests, I think we need to discuss the architecture of comments a bit, should we allow constant reply of comments(i.e. reddit style where you can reply to a specific comment or a reply and it constantly branches off from there) or like youtube where you just @ the person in the comments as a reply

I believe it should be more like YouTube. It's more of a personal preference for me, but I think it would be safer to implement for now and we can try testing out a branching method,

2024-11-11 08:01 UTC, misherwa commented
I modified the "to_representation" and "validate" methods in the  seralizers.py file. I added error handling for both. 

The error handling for "to_representation" can be found in the if statement right before "representation" gets returned. It is also in the CommentSerializer class.

"validate" is in the "CommentCreateSerializer" class, which includes "try and except" when issues if a comment or post doesn't exist

2024-11-12 19:59 UTC, thecatfour commented
Is there a test for checking if a hub owner/mod can delete a comment on a post in their hub? I can only find 2 delete tests that involve a non-author trying to delete a comment and the author trying to delete a comment. I think its important to make sure mods and owners can delete comments, so I think you should add those cases.

2024-11-13 01:05 UTC, misherwa commented
> Is there a test for checking if a hub owner/mod can delete a comment on a post in their hub? I can only find 2 delete tests that involve a non-author trying to delete a comment and the author trying to delete a comment. I think its important to make sure mods and owners can delete comments, so I think you should add those cases.

Gotcha, I updated the code to include test cases for when a hub owner or mod wants to delete a comment:
![org](https://github.com/user-attachments/assets/806688a3-e7a8-4bb0-a6e9-8a2614561930)


Note: I had to update the views.py file for Comments to include cases if a hub owner or mod wants to delete a comment. I also added a look_up field and set it to "comment_id".  It's similar  to how it's done in for views.py in Posts, so now the "CommentDelete" class looks like this:
![cur](https://github.com/user-attachments/assets/1b552c07-e550-480d-b684-d0e34f805a19)

2024-11-13 04:50 UTC, thecatfour commented
I'm not sure if including the .coverage file in the PR is necessary. It might cause conflicts similar to the ones we got earlier when trying to merge with the database file. Other than that, I think this includes all the tests that we need for the comments right now. If we include a view for editing a comment, we will need to add test cases for that though.

2024-11-13 10:25 UTC, nnguyen144 commented
> > Good tests, I think we need to discuss the architecture of comments a bit, should we allow constant reply of comments(i.e. reddit style where you can reply to a specific comment or a reply and it constantly branches off from there) or like youtube where you just @ the person in the comments as a reply
> 
> I believe it should be more like YouTube. It's more of a personal preference for me, but I think it would be safer to implement for now and we can try testing out a branching method,

YouTube comment styling is easier and just requires a link to the post and to another comment if the comment is a reply. I believe YouTube comment styling would be the way to go.

Like thecatfour said, we eventually would need to include some code for editing a comment. But that can be handled later. Otherwise your tests are good for now.

2024-11-13 10:37 UTC, nnguyen144 requested changes
I also noticed that you reversed a lot of urls that are not in urls.py, such as 
url = reverse("comments:like-comment", kwargs={"comment_id": reply.id})
Make sure you fix this.

2024-11-13 10:37 UTC, nnguyen144 commented on backend/Comments/tests.py
> +        other_user = User.objects.create_user(username='other_user', password='other_user_passwird')
Should be 'other_user_password' and not 'other_user_passwird'

2024-11-13 10:37 UTC, nnguyen144 commented on backend/Comments/tests.py
> +    def test_Moderator_deleting_comment(self):
Small nitpick but you could probably de-capitalize Moderator and Hub in the titles of these two tests

2024-11-13 10:48 UTC, nnguyen144 commented
Also since you added a new URL, can you add that URl to url-segments.ts

2024-11-15 22:52 UTC, thecatfour commented
> Also since you added a new URL, can you add that URl to url-segments.ts

I already implemented the new URLs in #67, so it should be the same whether they are added here or in that PR.

2024-11-15 22:58 UTC, thecatfour approved these changes
I believe this addresses what we need for the backend comments tests.

2024-11-16 00:46 UTC, misherwa commented
> I believe this addresses what we need for the backend comments tests.

I think I'll wait till your #67 PR gets merged and then make proper changes to this one.

2024-11-20 21:04 UTC, nnguyen144 approved these changes

2024-12-01 22:48 UTC, closed without merging